spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/subak
    username: root
    password: '0000'

logging:
  level:
    org.hibernate.SQL: debug